name: Daily Key Update

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at 00:00 UTC
  workflow_dispatch:      # Manual run button

jobs:
  update-key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run key generator
        env:
          MIKA_SECRET: ${{ secrets.MIKA_SECRET }}
        run: python generate_key.py

      - name: Commit and push updated key
        run: |
          git config user.name "MikaKeyBot"
          git config user.email "bot@mikahub.local"
          git add -A
          git commit -am "🔐 Auto-update key" || echo "Nothing to commit"
          git push
          
